=== nubok/XMulti/authors.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="authors">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="author">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="prename" type="xs:string" />
              <xs:element name="surname" type="xs:string" />
              <xs:element minOccurs="0" name="date_of_birth">
                <xs:complexType>
                  <xs:attribute name="year" type="xs:unsignedShort" use="required" />
                  <xs:attribute name="month" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="day" type="xs:unsignedByte" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nubok/XMulti/authors.xml
<?xml version="1.0" encoding="utf-8"?>
<authors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="authors.xsd">
  <!-- Die Autoren sind nicht alphabetisch sortiert, um zu testen, ob sie korrekt sortiert werden -->
  <author id="christian_romacker">
    <prename>Christian</prename>
    <surname>Romacker</surname>
  </author>
  <author id="wolfgang_keller">
    <prename>Wolfgang</prename>
    <surname>Keller</surname>
    <date_of_birth year="1986" month="5" day="8" />
  </author>
  <author id="john_doe">
    <prename>John</prename>
    <surname>Doe</surname>
  </author>
  <!-- An author with no article to test whether she will be hidden -->
  <author id="jane_doe">
    <prename>Jane</prename>
    <surname>Doe</surname>
  </author>
</authors>
